wechat_id: we-chat-tutorial #replace this with your wechat id
help_message: your help message
welcome_message:
  title: 微信公众账户开发指南
  picture: www.test.com
  description: 欢迎您关注微信公众账户开发指南
  link: linkedme.in
